spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service


server:
  port: 9788

---


spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: Asdf@1234


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uui}
  client:
    service-url: 
       default-zone: http://localhost:8761/eureka/
       
       
server:
  port: 8762
  
zuul:
  routes:
    product-service:
      path: /api/1.0/product/**
      serviceId: product-service
      strip-prefix: false
